# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'Examples' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Examples
  pod 'STPhotoMap', :git => 'https://github.com/mikelanza/st-photo-map-ios.git', :branch => 'develop'

  target 'ExamplesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ExamplesUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
