# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/mikelanza/st-photo-pod-specs.git'

target 'Examples' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Examples
  pod 'STPhotoMap', :git => 'https://github.com/mikelanza/st-photo-map-ios.git', :commit => '6e56010'
  
  
  target 'ExamplesTests' do
    inherit! :search_paths
    # Pods for testing
  end 

  target 'ExamplesUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
